## Deliverable 2. Create a Customer Travel Destinations Map.

In [1]:
# Dependencies and Setup
import pandas as pd
import requests
import gmaps
import numpy as np
import json

# Import API key
from config import g_key

# Configure gmaps API key
gmaps.configure(api_key=g_key)

In [13]:
# 1. Import the WeatherPy_database.csv file. 
city_data_df = pd.read_csv("../Weather_Database/WeatherPy_database.csv")
city_data_df.head()

,City ID,City,Country,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Current Description
0,0,Hilo,US,19.7297,-155.0900,73.27,68,1,8.05,clear sky
1,1,Maues,BR,-3.3836,-57.7186,98.80,34,100,3.56,overcast clouds
2,2,Spolaita,GR,38.6966,21.3464,72.99,44,0,3.44,clear sky
3,3,Camana,PE,-16.6228,-72.7111,66.36,71,19,8.57,few clouds
4,4,Ushuaia,AR,-54.8000,-68.3000,53.22,81,100,4.27,overcast clouds

In [15]:
# 2. Prompt the user to enter minimum and maximum temperature criteria 
max_temp = int(input("What is the maximum tempature you want on this vacation?" ))
min_temp = int(input("What is the minimum tempature you want on this vacation?" ))

What is the maximum tempature you want on this vacation?77
What is the minimum tempature you want on this vacation?55

In [16]:
# 3. Filter the city_data_df DataFrame using the input statements to create a new DataFrame using the loc method.
cities_max_temp = city_data_df.loc[(city_data_df["Max Temp"] <= max_temp) & (city_data_df["Max Temp"] >= min_temp)]
cities_max_temp

,City ID,City,Country,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Current Description
0,0,Hilo,US,19.7297,-155.0900,73.27,68,1,8.05,clear sky
2,2,Spolaita,GR,38.6966,21.3464,72.99,44,0,3.44,clear sky
3,3,Camana,PE,-16.6228,-72.7111,66.36,71,19,8.57,few clouds
6,6,Carnarvon,AU,-24.8667,113.6333,66.27,82,75,16.11,broken clouds
11,11,Albany,US,42.6001,-73.9662,68.85,71,23,1.01,few clouds
...,...,...,...,...,...,...,...,...,...,...
658,658,Waterloo,CA,43.4668,-80.5164,62.73,82,90,8.01,overcast clouds
662,662,Dijon,FR,47.3167,5.0167,75.31,46,0,3.44,clear sky
663,663,Maple Creek,CA,49.9168,-109.4848,59.41,26,19,2.30,few clouds
664,664,Ebolowa,CM,2.9000,11.1500,76.14,80,100,1.36,light rain
669,669,Litovel,CZ,49.7012,17.0762,65.68,66,51,13.33,broken clouds

In [17]:
# 4a. Determine if there are any empty rows.
cities_max_temp.count()

City ID                271
City                   271
Country                269
Lat                    271
Lng                    271
Max Temp               271
Humidity               271
Cloudiness             271
Wind Speed             271
Current Description    271
dtype: int64

In [45]:
# 4b. Drop any empty rows and create a new DataFrame that doesn’t have empty rows.
clean_df = cities_max_temp.dropna()
clean_df.count()

City ID                269
City                   269
Country                269
Lat                    269
Lng                    269
Max Temp               269
Humidity               269
Cloudiness             269
Wind Speed             269
Current Description    269
dtype: int64

In [19]:
# 5a. Create DataFrame called hotel_df to store hotel names along with city, country, max temp, and coordinates.
hotel_df = clean_df[["City", "Country", "Max Temp", "Current Description", "Lat", "Lng"]].copy()

# 5b. Create a new column "Hotel Name"
hotel_df["Hotel Name"] = ""
hotel_df.head(10)

,City,Country,Max Temp,Current Description,Lat,Lng,Hotel Name
0,Hilo,US,73.27,clear sky,19.7297,-155.0900,
2,Spolaita,GR,72.99,clear sky,38.6966,21.3464,
3,Camana,PE,66.36,few clouds,-16.6228,-72.7111,
6,Carnarvon,AU,66.27,broken clouds,-24.8667,113.6333,
11,Albany,US,68.85,few clouds,42.6001,-73.9662,
13,Airai,TL,59.32,overcast clouds,-8.9266,125.4092,
16,Mount Darwin,ZW,76.41,clear sky,-16.7725,31.5838,
17,Bredasdorp,ZA,61.29,scattered clouds,-34.5322,20.0403,
18,Bethel,US,69.35,broken clouds,41.3712,-73.4140,
20,Ponta Do Sol,PT,73.00,broken clouds,32.6667,-17.1000,

In [41]:
# 6a. Set parameters to search for hotels with 5000 meters.
lat= row["Lat"]
lng= row["Lng"]

params = {
    "radius": 5000,
    "type": "lodging",
    "key": g_key
}
base_url = "https://maps.googleapis.com/maps/api/place/nearbysearch/json"

# 6b. Iterate through the hotel DataFrame.
for index, row in hotel_df.iterrows():
    # 6c. Get latitude and longitude from DataFrame
    try:
        lat= row["Lat"]
        lng= row["Lng"]

        params["location"] = f"{lat},{lng}"

        coordinates = f"{lat}, {lng}" 
        # 6d. Set up the base URL for the Google Directions API to get JSON data.
        print(f"Retrieving Results for index {index}: {lat}, {lng}")
        # 6e. Make request and retrieve the JSON data from the search. \
        response = requests.get(base_url, params = params).json()
        results = response["results"]  
        # 6f. Get the first hotel from the results and store the name, if a hotel isn't found skip the city.
        hotel_df.loc[index, "Hotel Name"] = results[0]["name"]
        print(results[0]["name"])
    except:
        pass

Retrieving Results for index 0: 19.7297, -155.09
Hilo Hawaiian Hotel
Retrieving Results for index 2: 38.6966, 21.3464
ΕΞΟΧΙΚΟ ΚΑΠΕΛΗ
Retrieving Results for index 3: -16.6228, -72.7111
Hostal Morales
Retrieving Results for index 6: -24.8667, 113.6333
Hospitality Carnarvon
Retrieving Results for index 11: 42.6001, -73.9662
Retrieving Results for index 13: -8.9266, 125.4092
Juvinal Martin
Retrieving Results for index 16: -16.7725, 31.5838
Retrieving Results for index 17: -34.5322, 20.0403
Bredasdorp Country Manor
Retrieving Results for index 18: 41.3712, -73.414
Courtyard by Marriott Danbury
Retrieving Results for index 20: 32.6667, -17.1
Hotel do Campo
Retrieving Results for index 29: 23.306, 103.1635
Hongtai Commercial Hotel
Retrieving Results for index 32: -20.3297, -40.2925
Quality Suites Vila Velha
Retrieving Results for index 34: -9.4333, 159.95
Heritage Park Hotel
Retrieving Results for index 41: -20.4081, 57.7
Shandrani Beachcomber Resort & Spa
Retrieving Results for index 42: 50.3164, -122.8027
Pemberton Valley Lodge
Retrieving Results for index 47: -33.5906, 26.891
The Halyards Hotel
Retrieving Results for index 48: -21.2078, -159.775
Paradise Inn
Retrieving Results for index 49: 7.9986, 124.2928
Derogongan Residence
Retrieving Results for index 50: -23.1203, -134.9692
People ThankYou
Retrieving Results for index 51: 45.3167, 55.2
NUR
Retrieving Results for index 53: -20.3428, 57.7575
Casa Tia Villa
Retrieving Results for index 55: 38.2477, 36.914
Afsin Ogretmenevi ASO
Retrieving Results for index 58: -33.918, 25.5701
39 On Nile Guest House
Retrieving Results for index 59: -13.2325, 30.2352
The Kabaso's
Retrieving Results for index 60: 50.8552, 0.5729
Zanzibar Hotel
Retrieving Results for index 64: -34.4187, 19.2345
Misty Waves Boutique Hotel
Retrieving Results for index 65: -21.3585, 55.7679
Chambres d'hôte "La Trinité"
Retrieving Results for index 67: 50.4638, -3.5143
The Grand Hotel
Retrieving Results for index 70: -34.5833, 150.8552
Shellharbour Resort & Conference Centre
Retrieving Results for index 71: 4.1833, 19.9
Retrieving Results for index 73: 59.3556, 5.2242
Park Inn Haugesund Airport
Retrieving Results for index 74: -22.6667, 167.4833
Hotel Kou-Bugny
Retrieving Results for index 76: 42.097, -79.2353
Hampton Inn & Suites Jamestown
Retrieving Results for index 82: -43.5333, 172.6333
The George
Retrieving Results for index 83: 40.5982, -124.1573
Super 8 by Wyndham Fortuna
Retrieving Results for index 86: -25.2406, 130.9889
Desert Gardens Hotel - Ayers Rock Resort
Retrieving Results for index 87: 39.05, -27.9833
Casa Das Faias
Retrieving Results for index 97: -33.6971, -53.4616
Nuevo Hotel Plaza
Retrieving Results for index 100: -33.0153, 27.9116
Tu Casa
Retrieving Results for index 101: -27.0303, 28.6006
Niki's Guesthouse
Retrieving Results for index 107: -16.0999, 167.4164
Lakatoro Palm Lodge
Retrieving Results for index 108: 32.5341, 20.5791
Lagrota restaurant
Retrieving Results for index 116: -33.9258, 18.4232
Southern Sun Waterfront Cape Town
Retrieving Results for index 120: 43.7501, -81.7165
Harmony Inn
Retrieving Results for index 121: 40.2681, -96.747
Victorian Inn Beatrice
Retrieving Results for index 124: 41.3662, -81.8543
Comfort Inn Cleveland Airport
Retrieving Results for index 126: -9.0853, -78.5783
Hotel Viera Chimbote
Retrieving Results for index 129: 39.2667, 141.8833
Hotel Route Inn Kamaishi
Retrieving Results for index 130: -20.3167, 118.5667
The Esplanade Hotel
Retrieving Results for index 132: 41.2331, -80.4934
Buhl Mansion Guesthouse & Spa
Retrieving Results for index 133: 48.6499, -53.1147
Abbott's Bed & Breakfast
Retrieving Results for index 139: 46.4154, 3.9054
Manoir Du Bonheur
Retrieving Results for index 142: -21.2, -175.2
Keleti Beach Resort
Retrieving Results for index 144: -41.8697, -73.8203
Hotel Arena Gruesa
Retrieving Results for index 148: 37.15, 122.3833
GreenTree Hotel Rongcheng Bus Station
Retrieving Results for index 150: -28.7667, 114.6
Broadwater Mariner Resort
Retrieving Results for index 154: 21.3469, -158.0858
Marriott's Ko Olina Beach Club
Retrieving Results for index 156: -26.5333, 153.1
Palmer Coolum Resort
Retrieving Results for index 162: -35.3333, -72.4167
Hotel Boutique Las Azucenas
Retrieving Results for index 164: -23.65, -70.4
Holiday Inn Express Antofagasta, an IHG Hotel
Retrieving Results for index 165: -38.5473, -58.7368
dyd -mar Hotel
Retrieving Results for index 167: -18.475, -70.3042
Hostal Jardin Del Sol
Retrieving Results for index 169: -3.3667, 135.4833
Hotel Nusantara Nabire
Retrieving Results for index 174: -13.7, -76.2167
Hotel San Isidro Oficial
Retrieving Results for index 176: -29.9533, -71.3436
Punto de encuentro
Retrieving Results for index 177: 45.6169, -61.3485
MacKenzie House Tourist Home B&B
Retrieving Results for index 178: -22.2763, 166.4572
Hôtel Le Lagon
Retrieving Results for index 179: 27.9769, -114.0611
Casa Laguna, Bed & Breakfast
Retrieving Results for index 180: -34.0033, 24.7314
Oyster Bay House Rental
Retrieving Results for index 181: -20.0064, 57.6608
Veranda Paul et Virginie Hotel & Spa
Retrieving Results for index 188: 34.5, 62.0
Retrieving Results for index 189: 29.5833, -9.5
Retrieving Results for index 191: 35.7333, 140.8333
Hotel Sunrise Choshi
Retrieving Results for index 192: 40.7391, -114.0733
Motel 6 Wendover, UT
Retrieving Results for index 196: -11.0964, -77.6139
Hotel Villa Kitzia Huacho
Retrieving Results for index 198: -20.5167, 57.5167
Shanti Maurice Resort & Spa
Retrieving Results for index 204: 34.5686, 105.8933
Shell Tianshui Maiji District Erma Road Walking Street Hotel
Retrieving Results for index 205: 51.3813, 1.3862
Premier Inn Margate hotel
Retrieving Results for index 207: 50.8165, -119.6857
Chase Country Inn Motel
Retrieving Results for index 209: 46.4333, 26.4
Casa Mika Ciobanus
Retrieving Results for index 212: -23.7781, -45.3581
Ilha Flat Hotel
Retrieving Results for index 220: 53.3925, -2.5802
Patten Arms Hotel
Retrieving Results for index 222: -45.8742, 170.5036
Scenic Hotel Southern Cross
Retrieving Results for index 224: 39.1834, -84.5333
Six Acres Bed & Breakfast
Retrieving Results for index 225: -22.9661, -42.0278
Pousada Porto Praia
Retrieving Results for index 230: -38.0023, -57.5575
Gran Hotel Mar del Plata
Retrieving Results for index 232: -19.55, 169.2667
Tanna Lodge
Retrieving Results for index 236: -21.15, 149.2
International Lodge Motel
Retrieving Results for index 241: -26.6167, -54.1333
Complejo Turístico Farelluk
Retrieving Results for index 246: 37.4695, -105.87
Best Western Alamosa Inn
Retrieving Results for index 247: 41.7597, 86.1469
Gulisitan Hotel
Retrieving Results for index 249: 40.1629, -8.3327
Casa Maquia
Retrieving Results for index 254: 34.6667, 138.95
Shimoda Tokyu Hotel
Retrieving Results for index 255: 40.3758, 70.8156
Jamoliddinovlar oilasi
Retrieving Results for index 257: -16.4833, -151.75
Bora-Bora Pearl Beach Resort & Spa
Retrieving Results for index 258: 49.7834, -74.8492
Hôtel Opémiska
Retrieving Results for index 259: -0.9516, 122.7875
Hotel Santika Luwuk
Retrieving Results for index 261: 35.1333, 140.3
Katsuura Hotel Mikazuki
Retrieving Results for index 262: 38.4953, 102.1739
Mingshihui Jinchang International Hotel
Retrieving Results for index 264: -19.0595, -169.9187
Taloa Heights
Retrieving Results for index 265: -33.295, -66.3356
Huarpes Hotel
Retrieving Results for index 266: 11.1333, 39.6333
Joamla Hotel
Retrieving Results for index 267: -1.95, 18.2667
Hotel Du Lac
Retrieving Results for index 268: -0.7193, 8.7815
Fengshui Residence
Retrieving Results for index 270: 44.0777, -93.5074
American Motel
Retrieving Results for index 271: 43.6475, 111.9767
Erenhot Rurouni Youth Hostel
Retrieving Results for index 279: -34.6667, -54.9167
La Cimarrona
Retrieving Results for index 283: -19.9842, 57.6142
Pereybere Hotel & Spa
Retrieving Results for index 284: 36.6828, -101.4816
Super 8 Guymon
Retrieving Results for index 286: -37.6167, -73.65
Hostal Las Lilas
Retrieving Results for index 288: -28.65, 153.6167
Backpackers Inn on the Beach
Retrieving Results for index 292: 50.2334, -63.5986
Auberge Niapiskau
Retrieving Results for index 293: 5.3378, 116.1602
Sabindo Hotel
Retrieving Results for index 297: -12.0432, -77.0282

Gran Hotel Bolivar Lima
Retrieving Results for index 302: -21.3393, 55.4781
Lindsey Hôtel
Retrieving Results for index 303: 49.5833, 0.3333
gite bois jourdain
Retrieving Results for index 306: -10.0681, -78.1522
Hotel Miramar
Retrieving Results for index 308: -13.8745, -171.5986
Leuaina Beach Resort and Spa
Retrieving Results for index 309: 51.5877, -2.9984
ibis budget Newport
Retrieving Results for index 312: 36.1333, 137.25
Country Hotel Takayama
Retrieving Results for index 314: 28.1667, 94.7667
Hotel West
Retrieving Results for index 317: -21.6403, -41.0511
Pousada Porto De Canoas
Retrieving Results for index 318: -20.15, 28.5833
4 On Housman Backpackers
Retrieving Results for index 321: 42.0551, 59.3788
Мой дом
Retrieving Results for index 322: 33.3317, -105.673
Inn of the Mountain Gods
Retrieving Results for index 326: 36.7361, 69.5345
Saraisang street
Retrieving Results for index 331: 38.5167, -28.7
Quinta da Meia Eira
Retrieving Results for index 333: 20.8947, -156.47
Maui Seaside Hotel
Retrieving Results for index 336: 42.7762, -9.0603
Apartment Av. Castelao
Retrieving Results for index 337: 46.6166, 10.7002
Pension Feldgärtenhof
Retrieving Results for index 343: 46.4665, -120.6678
Retrieving Results for index 344: 51.0651, -1.3187
The Wykeham Arms, Winchester
Retrieving Results for index 346: 11.5936, 37.3908
Delano Hotel, Bahir Dar
Retrieving Results for index 350: 18.3851, 42.4509
املاك خالد الشعشوع
Retrieving Results for index 354: -23.865, 35.3833
Oceano
Retrieving Results for index 363: -34.0527, 23.3716
Thanda Vista B&B
Retrieving Results for index 364: 40.6576, -73.5832
The Freeport Inn and Marina
Retrieving Results for index 366: 52.8408, -6.9261
Seven Oaks Hotel
Retrieving Results for index 369: 34.6391, -120.4579
Holiday Inn Express Lompoc, an IHG Hotel
Retrieving Results for index 370: 42.1584, -72.3287
Wedgewood Motel
Retrieving Results for index 371: 34.2284, -92.0032
Holiday Inn Express & Suites Pine Bluff/Pines Mall, an IHG Hotel
Retrieving Results for index 373: -34.4833, -54.3333
Beleza Pura B&B
Retrieving Results for index 374: 51.0834, -115.3521
Blackstone Mountain Lodge by CLIQUE
Retrieving Results for index 379: -45.8667, -67.5
Austral Hotel
Retrieving Results for index 381: 40.81, 114.8794
Shell Zhangjiakou City Qiaodong District Ginza Hotel
Retrieving Results for index 382: -6.3164, 155.4848
Retrieving Results for index 384: 18.2164, 42.5053
Abha Hotel
Retrieving Results for index 385: 40.6334, -74.2663
Homewood Suites by Hilton Newark-Cranford
Retrieving Results for index 387: 4.9158, 29.4742
Retrieving Results for index 390: 41.7589, 69.3864
Retrieving Results for index 392: -2.65, 10.0
Retrieving Results for index 394: 51.064, -0.3272
Springfields Hotel
Retrieving Results for index 395: -0.3167, 102.35
Rumah mbah Jamah
Retrieving Results for index 396: 25.5198, 90.2201
Hotel RIKMAN Continental
Retrieving Results for index 398: -28.8667, 153.5667
Ramada Hotel & Suites by Wyndham Ballina Byron
Retrieving Results for index 400: -45.5752, -72.0662
Diego De Almagro Coyhaique
Retrieving Results for index 405: -3.945, 122.4989
Hotel Wixel
Retrieving Results for index 409: 39.5994, -110.8107
National 9 - Price River Inn
Retrieving Results for index 411: 37.7167, -25.4333
Pestana Bahia Praia
Retrieving Results for index 412: 39.8161, 109.9776
Crowne Plaza Ordos
Retrieving Results for index 414: 51.0333, -4.2167
Durrant House Hotel
Retrieving Results for index 416: 36.6177, -121.9166
Lovers Point Inn
Retrieving Results for index 419: -25.2986, 152.8535
Shelly Bay Resort
Retrieving Results for index 420: -8.4667, 140.3333
Retrieving Results for index 423: 49.2664, 8.6167
Leonardo Hotel Heidelberg-Walldorf
Retrieving Results for index 430: 34.388, 67.0233
Retrieving Results for index 434: 38.7992, -9.4469
Arribas Sintra Hotel
Retrieving Results for index 435: 39.0375, 65.585
Retrieving Results for index 437: -3.6954, 128.1814
Swiss-Belhotel Ambon
Retrieving Results for index 438: 41.4501, -71.4495
Hampton Inn South Kingstown - Newport Area
Retrieving Results for index 444: -0.9131, 122.8766
Penginapan Kim
Retrieving Results for index 446: 35.2442, 129.2139
Samyang Beach Villa
Retrieving Results for index 447: -32.55, 115.7
Atrium Hotel Mandurah
Retrieving Results for index 448: 30.5255, -89.6795
Holiday Inn Express & Suites Picayune
Retrieving Results for index 449: 8.7667, -82.6333
Hostal Victoria Volcan Chiriqui
Retrieving Results for index 451: -2.6833, 111.6167
Grand Kecubung Hotel
Retrieving Results for index 452: 38.7333, -27.0667
Hotel Branco I
Retrieving Results for index 457: 42.2068, -121.7372
Microtel Inn & Suites by Wyndham Klamath Falls
Retrieving Results for index 462: 23.2281, 110.8261
Retrieving Results for index 464: 17.4897, 104.1006
ร้านช่างเจมส์ สแตนเลส ประตู อื่นๆ คอกซิ่ง นาหว้านครพนม
Retrieving Results for index 466: 44.9894, 14.9058
Roza Guest House
Retrieving Results for index 468: 49.1447, 56.4872
Sirius
Retrieving Results for index 473: -36.3132, -57.6792
Apart Hotel - Arianos
Retrieving Results for index 474: -22.1333, 48.0167
La Residence Manakara
Retrieving Results for index 478: -15.5333, 167.1667
The Espiritu Hotel
Retrieving Results for index 481: 45.0334, -79.3163
BRACEBRIDGE INN
Retrieving Results for index 484: 34.6851, 135.8049
Guesthouse Nara Komachi
Retrieving Results for index 485: -17.8786, 36.8883
Hotel Flamingo
Retrieving Results for index 486: 46.7216, -92.4594
Super 8 by Wyndham Cloquet
Retrieving Results for index 488: 39.2048, -84.428
Motel 6 Cincinnati, OH - Central - Norwood
Retrieving Results for index 489: 48.3855, 18.4006
Hotel HRADNÁ STRÁŽ
Retrieving Results for index 492: -15.8631, -38.8828
Pousada Monte Carmelo O Pão
Retrieving Results for index 493: 25.1072, 117.0225
Jinjiang Inn Longyan Zhongshan Road Pedestrian Street
Retrieving Results for index 494: 42.9019, 133.9064
Campsite Orlan
Retrieving Results for index 496: 58.2093, -6.3865
Caladh Inn
Retrieving Results for index 497: 62.3096, 6.9358
Stranda Feriesenter
Retrieving Results for index 499: 4.4333, 14.3667
Hotel Hollywood
Retrieving Results for index 501: 33.194, -82.5271
Retrieving Results for index 502: -22.9, 44.5333
Le Relais
Retrieving Results for index 503: 51.55, -9.2667
The West Cork Hotel
Retrieving Results for index 504: -37.3217, -59.1332
HOSTAL DE LA SIERRA TANDIL
Retrieving Results for index 507: 42.8, 93.45
Laoyutang Resort
Retrieving Results for index 512: 25.5333, -103.25
Quinta Belem
Retrieving Results for index 513: -5.5502, 150.1429
Kimbe Bay Hotel
Retrieving Results for index 515: 41.3114, -105.5911
Fairfield Inn & Suites by Marriott Laramie
Retrieving Results for index 519: 34.9833, 139.8667
Tateyama Seaside Hotel
Retrieving Results for index 521: 32.3502, -85.1999
Macs
Retrieving Results for index 522: 22.9167, 96.5
MOGOK HILL HOTEL
Retrieving Results for index 523: 5.5263, 7.4896
Hotel Macbek Limited
Retrieving Results for index 525: 37.4, 136.9
Wajiima Onsen Yashio
Retrieving Results for index 527: 37.7903, 26.7044
Hotel Aegeon
Retrieving Results for index 529: 48.3833, -4.6167
Carrefour Voyages Plouzané
Retrieving Results for index 531: -16.0667, 167.3833
Nabelchel Bungalows
Retrieving Results for index 532: 36.9559, 36.2
Artemis Otel
Retrieving Results for index 533: 6.5167, 14.3
DFR HOUSE
Retrieving Results for index 534: -9.3333, 33.75
Retrieving Results for index 535: 45.0205, -93.218
Holiday Inn Express Roseville-St. Paul, an IHG Hotel
Retrieving Results for index 539: -15.1961, 12.1522
Hotel Chik Chik Namibe
Retrieving Results for index 540: 37.5133, 34.0467
Hotel Fuat Bey
Retrieving Results for index 541: -20.2078, 57.7625
Sunrise Attitude Hotel
Retrieving Results for index 542: 32.7701, -108.2803
Copper Manor Motel
Retrieving Results for index 546: 41.1239, -100.7654
Holiday Inn Express & Suites North Platte, an IHG Hotel
Retrieving Results for index 550: 55.1333, -6.6667
The Lodge Hotel
Retrieving Results for index 556: 35.3947, 116.0883
Thank Inn Chain Hotel shandong heze juye county shanghai jiayuan
Retrieving Results for index 557: -3.8004, 102.2655
Grage Hotel Bengkulu
Retrieving Results for index 558: 45.4375, 40.5756
Hotel Europe Kropotkin
Retrieving Results for index 562: 10.0667, 34.5333

Blendana Hotel Assosa
Retrieving Results for index 567: -8.7676, 160.7034
Auki Motel
Retrieving Results for index 571: 51.1786, 49.6769
Korolevskiy Dvor
Retrieving Results for index 572: -20.5833, 48.5333
Hotel Volazara
Retrieving Results for index 574: -21.3667, 55.6167
"Plantation Bed and Breakfast
Retrieving Results for index 577: 34.1667, 77.5833
Hotel Ladakh Greens
Retrieving Results for index 579: 51.1834, -114.4687
Days Inn & Suites by Wyndham Cochrane
Retrieving Results for index 580: 3.9833, 13.1833
Auberge Angle Sur
Retrieving Results for index 581: -20.5667, 164.2833
Le Monitel
Retrieving Results for index 582: 42.1167, 118.7833
Jinjiang Hotel
Retrieving Results for index 584: -25.4, -70.4833
Residencial Karime
Retrieving Results for index 585: 55.3422, -131.6461
Snow's Cove Lodge
Retrieving Results for index 589: 0.5412, 123.0595
Maqna Hotel by Prasanthi
Retrieving Results for index 592: 41.6336, 46.6433
Ag Bina Hotel & Spa
Retrieving Results for index 593: 44.69, 37.59
Avgustin Inn
Retrieving Results for index 594: -17.0, 145.4333
Trinity Plains Tourist Park
Retrieving Results for index 595: 42.7297, 133.0839
Отель "БАЛИ"
Retrieving Results for index 596: 47.2167, 22.5667
Hotel Alex
Retrieving Results for index 602: -42.7692, -65.0385
Hotel Tolosa
Retrieving Results for index 604: 28.6585, -17.9182
Valle Aridane
Retrieving Results for index 608: -12.2333, 136.7667
East Arnhem Real Estate
Retrieving Results for index 609: -31.395, -52.6756
Casa Paulista
Retrieving Results for index 616: -43.3002, -65.1023
Hosteria Sampedro
Retrieving Results for index 617: -28.0611, -50.9383
Retrieving Results for index 618: -14.2667, 50.1667
Melrose
Retrieving Results for index 624: 4.095, 30.6779
City Link Hotel
Retrieving Results for index 626: 38.9342, 100.4517
Zhangye Lvzhou Holiday Inn
Retrieving Results for index 627: 37.5683, 126.9778
Lotte Hotel Seoul
Retrieving Results for index 628: 41.1231, 80.2644
Pudong Holiday Hotel
Retrieving Results for index 634: 30.2833, 78.9833
OYO 66654 Hotel Devlok
Retrieving Results for index 641: 51.1631, 54.9918
Raduzhnaya
Retrieving Results for index 644: -2.4177, 115.2494
Hotel Balqis
Retrieving Results for index 650: 40.3639, 50.215
Samir Зона Отдыха
Retrieving Results for index 652: -25.1667, 46.0833
RELAHARA
Retrieving Results for index 653: 41.8447, 60.3919
ÒJIQ OVUL
Retrieving Results for index 654: -8.4667, 118.7167
Lambitu Hotel
Retrieving Results for index 655: 43.6125, 122.2653
Meirujia Hotel
Retrieving Results for index 657: -33.0117, 17.9442
Blue Bay Lodge
Retrieving Results for index 658: 43.4668, -80.5164
Comfort Inn
Retrieving Results for index 662: 47.3167, 5.0167
Hôtel Restaurant Campanile Dijon Gare
Retrieving Results for index 663: 49.9168, -109.4848
Willowbend Campground & Cabins
Retrieving Results for index 664: 2.9, 11.15
Florence Hotel Ebolowa
Retrieving Results for index 669: 49.7012, 17.0762
Ubytovna U Šmoldasů

In [73]:
# 7. Drop the rows where there is no Hotel Name.
hotel_df.loc[hotel_df["Hotel Name"] == ""] = np.nan
clean_hotel_df = hotel_df.dropna()
clean_hotel_df

,City,Country,Max Temp,Current Description,Lat,Lng,Hotel Name
0,Hilo,US,73.27,clear sky,19.7297,-155.0900,Hilo Hawaiian Hotel
2,Spolaita,GR,72.99,clear sky,38.6966,21.3464,ΕΞΟΧΙΚΟ ΚΑΠΕΛΗ
3,Camana,PE,66.36,few clouds,-16.6228,-72.7111,Hostal Morales
6,Carnarvon,AU,66.27,broken clouds,-24.8667,113.6333,Hospitality Carnarvon
13,Airai,TL,59.32,overcast clouds,-8.9266,125.4092,Juvinal Martin
...,...,...,...,...,...,...,...
658,Waterloo,CA,62.73,overcast clouds,43.4668,-80.5164,Comfort Inn
662,Dijon,FR,75.31,clear sky,47.3167,5.0167,Hôtel Restaurant Campanile Dijon Gare
663,Maple Creek,CA,59.41,few clouds,49.9168,-109.4848,Willowbend Campground & Cabins
664,Ebolowa,CM,76.14,light rain,2.9000,11.1500,Florence Hotel Ebolowa
669,Litovel,CZ,65.68,broken clouds,49.7012,17.0762,Ubytovna U Šmoldasů

In [74]:
results[0]["name"]

'Ubytovna U Šmoldasů'

In [76]:
# 8a. Create the output File (CSV)
# 8b. Export the City_Data into a csv
output_data_file = "clean_hotel.csv"
clean_hotel_df.to_csv(output_data_file, index_label="City_ID")

In [81]:
# 9. Using the template add city name, the country code, the weather description and maximum temperature for the city.
info_box_template = """
<dl>
<dt>Hotel Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
<dt>Max Temp</dt><dd>{Max Temp} °F</dd>
</dl>
"""

# 10a. Get the data from each row and add it to the formatting template and store the data in a list.
hotel_info = [info_box_template.format(**row) for index, row in clean_hotel_df.iterrows()]

# 10b. Get the latitude and longitude from each row and store in a new DataFrame.
locations = clean_hotel_df[["Lat", "Lng"]]
max_temp = clean_hotel_df["Max Temp"]
fig = gmaps.figure(center = (30.0,31.0), zoom_level = 1.5)
heat_layer = gmaps.heatmap_layer(locations, weights = max_temp, dissipating = False, 
                             max_intensity = 300, point_radius = 4)

In [83]:
# 11a. Add a marker layer for each city to the map. 
marker_layer = gmaps.marker_layer(locations, info_box_content= hotel_info)
# 11b. Display the figure
fig.add_layer(heat_layer)
fig.add_layer(marker_layer)
fig

Figure(layout=FigureLayout(height='420px'))